Add a non minified version of autoComplete.js
kiwix/libkiwix pull request #1008
Opened 2023-10-20 14:51 UTC by mgautierfr

Fix #819

2023-10-21 09:04 UTC, veloman-yunkan requested changes
I think it's time to define the procedure of how parts from other open source projects must be imported into OpenZIM &/| Kiwix projects. Questions to consider:

1. How and where attribution should be made? Is a mention in README enough or we have to include it in every imported file? If more than one file is imported maybe we should place them under their own subdirectory and only add a single `ATTRIBUTION.md` file? Should there be any difference between files that are only used during build vs those files that are exposed to the end-user?
2. Similar questions for the license of imported files.
3. Regarding sources (`autoComplete.js` in this case) and end-user-artifacts (`autoComplete.min.js` in this case) - having both files without the process that produces the latter from the former doesn't fully meet the justification for preserving the original sources in our own project/repository. In the light of that argument, do we really have to import the sources too? If yes, in which situations?

2023-11-04 11:04 UTC, kelson42 requested changes
It seems we should also put the license of this piece of code

2023-11-07 10:16 UTC, mgautierfr commented on static/skin/css/autoComplete.css
> +/* Modified from https://github.com/TarekRaafat/autoComplete.js (version 1.2.6)*/
1. Done
2. `autoComplete.css` is modified from original `autoComplete.css` so the small header. Other files (js) are not modified and so I prefer not change them.
3. Done

2023-11-07 10:26 UTC, veloman-yunkan approved these changes

2023-11-07 19:41 UTC, kelson42 approved these changes

2023-11-07 19:41 UTC, merged