Use title snippets if available
kiwix/libkiwix pull request #505
Opened 2021-05-08 19:30 UTC by maneeshpm

Fixes #82 

With openzim/libzim#545 we now support snippet generation for titles. It can be used as the display label on the ui for highlighted titles via the "label" field. The old version used plain-title which is still available in the value field.

Changes included in this pr:
- Sets `label` to title snippet if available

2021-05-09 05:16 UTC, kelson42 commented
@MananJethwani Maybe you can help @maneeshpm on that one?

2021-05-09 07:09 UTC, MananJethwani commented
this I suppose is a problem with jquery-ui. because the data is received in taskbar.js as we expect it to be, and to stop this behavior we might have to use [_renderItem](https://api.jqueryui.com/autocomplete/#method-_renderItem) property of autocomplete UI.

2021-05-10 06:50 UTC, MananJethwani commented
@maneeshpm `jquery-ui.js` is the library file from where we import suggestion system.

2021-05-10 07:42 UTC, maneeshpm commented
Thanks a lot for your help @MananJethwani, front end is not really my strong point :sweat_smile:  

Final result of the modification:
![Screenshot from 2021-05-10 12-56-32](https://user-images.githubusercontent.com/45821104/117623377-563acb00-b191-11eb-9d2d-c313bf1380d7.png)


@kelson42 I believe this feature can be improved further by modifications in stemming and stopwords(openzim/libzim#324) to ensure all the matching terms are highlighted.

2021-05-10 10:59 UTC, kelson42 commented
@maneeshpm Great to see this implemented and great you see the connection to the other ticket :)

2021-05-12 12:44 UTC, mgautierfr requested changes

2021-05-12 12:44 UTC, mgautierfr commented on src/reader.cpp
> +      suggestion.push_back(current.get_snippet());
Maybe it is time to introduce a class/struct for the suggestion result instead of using a vector of strings.

2021-05-16 05:41 UTC, maneeshpm commented
Rebasing temporarily on #526

2021-05-17 16:04 UTC, mgautierfr requested changes

2021-05-17 16:04 UTC, mgautierfr commented on include/reader.h
> +      snippet(snippet) {}
This is useless for the user to create a suggestion itself.
It is better to make the constructor private and add the `Reader` as friend class.

2021-05-19 04:56 UTC, kelson42 commented
@maneeshpm rebasing maybe?

2021-05-25 14:31 UTC, kelson42 commented
@mgautierfr I have rebased this branch. We should really review/merge.

2021-05-26 09:00 UTC, mgautierfr approved these changes

2021-05-26 09:04 UTC, mgautierfr commented
Rebased-fixup on master (and fix conflicts). We are good.

2021-05-26 09:04 UTC, merged