OpdsCatalog::getSearchUrl()
kiwix/libkiwix pull request #527
Opened 2021-05-15 21:37 UTC by veloman-yunkan

Fixes #480.

Must be merged after #526.

This is a **preliminary** implementation of OPDS search url generation targeting the new API introduced by the yet unmerged #492.

Note that #488 has enabled us to search by all fields via the query parameter. For example a search by category can be done in two ways:
1. (old) `search_endpoint?category=whatever`
2. (new) `search_endpoint?q=category:whatever`

Internally, the old approach is converted to an equivalent of the new one with the slight difference of not assuming partial query (which is the default mode for the `q` parameter).

Some fields (creator, publisher) are not exposed for searching in the old scheme but are available via the new scheme.

Now the question is which one of the two schemes should be utilized for the search URL generation?

Another question is what should be done about the filtering criteria `Filter::local()`, `Filter::remote()`, `Filter::remote()`? They have never been exposed through the OPDS search API.

TODOs:
- Don't ignore the `Filter::maxSize()` & `Filter::rejectTags()` filtering criteria.

2021-05-16 04:52 UTC, kelson42 commented
@veloman-yunkan Thx, do you have a kiwix-desktop related PR, so I can just test if it works (no regression) from user perspective?

2021-05-16 07:10 UTC, veloman-yunkan commented
> @veloman-yunkan Thx, do you have a kiwix-desktop related PR, so I can just test if it works (no regression) from user perspective?

No. It won't work until the new OPDS catalog API is merged and goes live on `library.kiwix.org` (or you will have to test with a custom-built `kiwix-serve` incorporating #492).

2021-05-16 07:13 UTC, kelson42 commented
@veloman-yunkan Really hard to me then to verify it works fine from a user persective. Will let @mgautierfr do the review.

2021-05-17 17:00 UTC, mgautierfr requested changes
> Now the question is which one of the two schemes should be utilized for the search URL generation?

I prefer the old one. Mainly because it is easier to read.

2021-05-25 19:46 UTC, veloman-yunkan commented
@kelson42 I will finalize this PR after #492 is merged (which introduces new catalog API that is assumed here).

2021-06-09 12:22 UTC, veloman-yunkan commented on src/opds_catalog.cpp
> +    return opdsSearchEndpoint + ("?" + searchString);
I tried it but didn't like the result. `getSearchUrl()` starts looking like a plagiarist that delegates all work to a ghost writer but receives all the credit. The current division of work between `getSearchUrl()` and `buildSearchString()` is more balanced.

2021-06-16 04:09 UTC, kelson42 commented
@veloman-yunkan #492 has been merge, I guess nothing stops us anymore to finish this PR?

2021-06-16 10:29 UTC, veloman-yunkan commented
@kelson42 This PR is finished and pending review by @mgautierfr

2021-06-16 13:47 UTC, mgautierfr commented
Nothing to say on the code.

I'm a bit less sure about the generated endpoint.
As the catalog V2 is not totally finalized, we may change the endpoints and we agree to not use them until we finish it (at least until we are confident enough to tell we can start us it).
If `getSearchUrl` use the v2 and we do a release with `getSearchUrl` then user will start to use it and start to use the v2 catalog. We have to be careful with this.

I will not block this PR for this, but I may block the next release however :slightly_smiling_face:

2021-06-30 16:28 UTC, mgautierfr commented
rebase/fixup on master.

This PR is open for two long now. As we agree on the code we can merge it.
We will discuss again this v2 endpoint when we will do the release.

2021-06-30 16:28 UTC, mgautierfr approved these changes

2021-06-30 19:35 UTC, merged