Introduce Search/Searcher Caching to Internal Server
kiwix/libkiwix pull request #620
Opened 2021-10-12 10:38 UTC by maneeshpm

Fixes #509 
This PR consists of three commits which are as follows:
- Add a general-purpose LRU cache template

This general-purpose LRU cache template can be used to implement caching for various classes with various cache size limits.
NOTE: One must think about thread safety and race condition while using the template.

- Implement caching on `Searcher` and `Search`

We use the new cache template to implement two kind of cache.
1: The `Searcher` cache is more general in terms of its usage. A `Searcher` can be used for multiple searches without much change to itself. We try to retrieve the `Searcher` and perform searches using it whenever possible, and if not we put a `Searcher` into the cache. Users can specify a custom cache length by manipulating the environment variable `SEARCHER_CACHE_SIZE`. Its default value is 10% of all the books available.
2: The `Search` cache is much more restricted in terms of usage. Its main purpose is to avoid re-searching on the `Searcher` during page changes to generate `SearchResultSet` of various ranges. Users can specify a custom cache length using the environment variable `SEARCH_CACHE_SIZE` with a default value of 2.

- Implement caching on `SuggestionSearcher`

We create a cache for `SuggestionSearcher` very similar to that of FT searcher. User can specify a custom cache size using the environment variable `SUGGESTION_SEARCHER_CACHE_SIZE`. It has a default value of 10% of the number of books in the library.

2021-11-01 07:14 UTC, maneeshpm commented on src/server/internalServer.cpp
> +    searcher = make_shared<zim::SuggestionSearcher>(*archive);
Yes, setting the verbosity to true, we can see that when we make a new searcher, we get
```
Parsed query 'song+for+you' to Query((((Zsong@1 AND Zfor@2 AND (WILDCARD SYNONYM you OR Zyou@3)) OR (song PHRASE 3 for PHRASE 3 you)) OR (0posanchor PHRASE 4 song PHRASE 4 for PHRASE 4 you)))
```
But when we retrieve the searcher from cache, 
```
Parsed query 'song+for+you' to Query((((song@1 OR for@2 OR (WILDCARD SYNONYM you OR you@3)) OR (song PHRASE 3 for PHRASE 3 you)) OR (0posanchor PHRASE 4 song PHRASE 4 for PHRASE 4 you)))
```

this is a bit puzzling for me, looking into the issue.

2021-11-01 09:17 UTC, maneeshpm commented on src/server/internalServer.cpp
> +    searcher = make_shared<zim::SuggestionSearcher>(*archive);
@mgautierfr found and fixed the issue in openzim/libzim#644

2021-11-10 11:04 UTC, mgautierfr requested changes
There are still few changes to do but we are mostly good.

2021-11-27 12:03 UTC, maneeshpm commented on src/server/internalServer.cpp
> +}
I agree we should not try to make this function "smart". I think for this function, all it should do is return the env val(if found) or the default val.

The comparison with 1 should be done at the point of call as you mentioned.

2021-11-29 16:05 UTC, mgautierfr requested changes
See my comments on the code.

But I've one comment coming from you, in the first commit message :
> NOTE: One must think about thread safety and race condition while using
the template.

2021-11-29 16:05 UTC, mgautierfr commented on src/server/internalServer.cpp
> +  searchCache(std::max(getCacheLength("SEARCH_CACHE_SIZE", SEARCH_CACHE_SIZE), 1U))
It should be valid for the user to set the env variable `SEARCH_CACHE_SIZE` to 0 (and so deactivate the cache).
So the searchCache should not have any `max`. And the `max`should be applied to the `getBookCount` only :
```cpp
searcherCache(getCacheLength("SEARCHER_CACHE_SIZE", std::max(mp_library->getBookCount(true, true)*0.1), 1U)),
searchCache(getCacheLength("SEARCH_CACHE_SIZE", SEARCH_CACHE_SIZE))
```

2021-11-29 16:05 UTC, mgautierfr commented on src/server/internalServer.cpp
>  // TODO: retrieve searcher from caching mechanism
We can remove this TODO.

2021-11-30 15:33 UTC, maneeshpm commented on src/server/internalServer.cpp
> +#define SEARCH_CACHE_SIZE 2
I don't understand your comment about my comment on thread safety?

2021-11-30 15:41 UTC, maneeshpm commented on src/server/internalServer.cpp
> +    return (unsigned int) atoi(envString);
Do we want to revert to the `defaultVal` in case there is an invalid argument?

2021-12-01 16:27 UTC, mgautierfr commented
> I don't understand your comment about my comment on thread safety?

In the commit where you introduce the cache system, you write :

> NOTE: One must think about thread safety and race condition while usingthe template.

I agree with you.
But then, in other commits, you don't protect the calls against race condition.
The server handles the requests in different threads, and so you must "think about thread safety and race condition" (and protect/modify the code accordingly)

2021-12-07 03:11 UTC, kelson42 commented
@maneeshpm Any news on this PR?

2021-12-07 13:02 UTC, maneeshpm commented
@mgautierfr aah ohk, so we are protecting suggestions module via mutex lock in libzim. You mean we need to do a similar treatment for FT search as well?

@kelson42 Sure, will do something about it.

2021-12-07 13:53 UTC, mgautierfr commented
> You mean we need to do a similar treatment for FT search as well?

I was thinking about protecting the cache system (you explicitly say that in your commit message) but yes, we also need to protect the FT search.

2021-12-15 09:42 UTC, mgautierfr commented
I wonder if we should move the searcher/suggestionSearcher cache in the library itself (as for the readers/archives)
It would simplify a bit the code with a `Library` method to get the searcher from a bookId (or even better, a book name if we also move the namemapper into the library (not sure we need to do this in this pr)).

---

The mutex protection you've added is not enough. It is technically protect the internal structures but a race condition is still possible :
- Two threads can try to get a searcher for book foo.
- The two threads cannot found it.
- They both create a searcher.
- They both add the searcher to the cache.
- Only one is added to the cache, but we use two different searcher. And when we create a search and put it in the cache, they will use two different searchers.

What we also need is to protect (block) the cache while we are creating the searcher to avoid the creation of two searcher.
It is not easy to do (if we want to do it efficiently). But we already have a implementation in libzim (https://github.com/openzim/libzim/blob/master/src/concurrent_cache.h) we may reuse it.

2021-12-15 16:35 UTC, maneeshpm commented
> I wonder if we should move the searcher/suggestionSearcher cache in the library itself

@mgautierfr I agree, we are anyway pulling in the archive from the library, so it is more natural to get the searchers(and search via cache or otherwise)  from the library itself rather than keeping it associated with the internal server. I propose we do it in a separate ticket after this.

Thanks for the suggestion, I'll get to see the proper implementation of an LRU cache rather than a simple one :sweat_smile: : I guess `concurrent_cache.h` in libzim is well written and tested!

2021-12-16 20:32 UTC, maneeshpm commented
@mgautierfr Implemented the concurrent cache version. Any idea whats going on in macOS? and how to get stoi to work on android_arm?

2021-12-17 09:24 UTC, kelson42 commented
@maneeshpm I suspect that `stoi` is only available in ndk16, see https://stackoverflow.com/a/42082899. We are still using ndk13. Maybe we should move on to 16?

2021-12-18 05:40 UTC, maneeshpm commented
@kelson42 you might be right, but we are already using stoi in [some files](https://github.com/kiwix/libkiwix/blob/90910c5cabcf3e5596545496379ebef31f4e22a6/test/httplib.h#L3770) and they seem to compile fine. Is there any other header to be included other than `<string>`?

2022-01-05 14:34 UTC, kelson42 commented
@mgautierfr Any feedback on this PR, considering how important is this PR improvement, would be really great if we would have a chance to achieve to merge it before 10.0.0 release!

2022-01-05 15:42 UTC, mgautierfr commented
> @kelson42 you might be right, but we are already using stoi in some files and they seem to compile fine. Is there any other header to be included other than <string>?

`stoi` is indeed missing. It is used in httplib but it is a small file (independent from our project) we use only to do request during the unit test. It is not used on android

There is the `extractFromString` function to replace `stoi`
https://github.com/kiwix/libkiwix/blob/master/src/tools/stringTools.h#L63-L69

```cpp
int value = extractFromString<int>("5");
```


I don't know what is the problem on macOs, we need to run the test using a debugger to check what is the problem.

2022-01-08 10:33 UTC, kelson42 commented
@rgaudin @automactic Any clue why this specific automated test fails only on macOS?

2022-01-08 11:10 UTC, maneeshpm commented
@kelson42 I have traced the error to the newly added function `getCacheLength()` that is supposed to read an environment variable and return its value(if found) or return a default value provided by the user. Returning a hardcoded number in the function such as `1` causes the error to go away. I am not really sure why that function fails on mac.

2022-01-08 11:12 UTC, kelson42 commented
I wonder why in a first place we deal with an ENV variable here?

2022-01-08 11:16 UTC, kelson42 commented
@maneeshpm But we have this kind of behaviour already in libzim and it works fine with macOS, maybe you could have a look to how this is done there?

2022-01-09 12:51 UTC, maneeshpm commented
Apparently, this problem was caused by a simple nullptr in returned by `getenv()`. Handling that case separately rather than relying on the try catch block fixes the problem.

I am not sure of a technical explanation for why this is not a problem on linux but on mac, maybe @mgautierfr can help with one :sweat_smile:

2022-01-09 13:01 UTC, kelson42 commented
@mgautierfr I see this ticket is ready for final review pass!

2022-02-28 15:32 UTC, kelson42 commented
@mgautierfr Considering that there is really not much to do and that @maneeshpm seems not available for the moment. Please feel free to just fix and merge.

2022-03-08 17:11 UTC, mgautierfr approved these changes

2022-03-08 17:12 UTC, mgautierfr commented
I've rebase on master and redo a bit the first commit which is a copy of file from libzim.
I haven't changed the other commits from @maneeshpm

2022-03-08 17:12 UTC, merged