Clickable kiwix-serve tiles
kiwix/libkiwix pull request #628
Opened 2021-10-30 15:47 UTC by kelson42

Fixes #627

2021-10-30 17:02 UTC, kelson42 commented
@mgautierfr Your point about the language code is clear but I have mixed feelings about that so I made a really light change which I hope goes in the right direction. But, I have no clue why macOS CI fails.
@MananJethwani Please let me know if I don't have broken something. After a bit of usage we have decided to slightly change things on the tiles.

2021-11-03 09:25 UTC, mgautierfr requested changes
This is far better than previously.

- The code factor error must be (easily) fixed.
- I would add a small round corner (1px should be enough) around the download button. I found the current version a bit rough.

I confirm the removing of the border around the tag lang, it make the tag a bit less like a button.

2021-11-16 13:07 UTC, mgautierfr approved these changes

2021-11-16 13:07 UTC, merged

2021-11-16 13:13 UTC, rgaudin commented
Fixed the codefactor issue and added the rounded border suggested by @mgautierfr