Do escape searchURL in full text search suggestion
kiwix/libkiwix pull request #721
Opened 2022-03-01 11:45 UTC by juuz0

Previously, the seachURL was not escaped.
This resulted in an XSS vulnerability, a concept of proof is:

start kiwix-serve
visit - http://192.168.18.1:8081/"><svg onload="alert(1)">
This would display an alert message.

This commit removes that behaviour by using inbuilt mustache escaping

2022-03-01 13:27 UTC, kelson42 requested changes
Unit tests are broken and it seems you PR encode `&` URL sepearator and it should not.

2022-03-02 10:55 UTC, mgautierfr requested changes
I wonder if this is the right place to secure the url. At least we already have a function to url encode a string (`urlEncode`), we should use it.

2022-03-02 10:55 UTC, mgautierfr commented on src/server/internalServer.cpp
> +  searchURL = replaceRegex(searchURL, "&gt;", ">");
We should replace `<` and `>` with the url encoding equivalent, not the html encoding.
This is a url and we want it to work for articles with `<`/`>` in it (at least be able to search for them)

2022-03-03 14:38 UTC, mgautierfr requested changes

2022-03-03 14:38 UTC, mgautierfr commented on src/server/internalServer.cpp
> +    std::string searchURL = kiwix::urlEncode(m_root + "/search?pattern=" + pattern); // Make a full search on the entire library.
There is another flaw here, it is possible to forge a specific url with:
`tld/foo&content=bar`, we will generate a link to `tld/search?pattern=foo&content=bar`.
It is less important that inserting a js in the page but we should fix it anyway.ç
The solution is probably to urlEncode only the pattern with `encodeReserved` at true.

2022-03-07 13:22 UTC, mgautierfr approved these changes

2022-03-09 13:33 UTC, kelson42 approved these changes

2022-03-09 13:33 UTC, merged

2022-03-18 14:21 UTC, legoktm commented
@juuz0 @kelson42 do we know what version the XSS vulnerability was introduced in?

2022-03-18 15:32 UTC, kelson42 commented
@legoktm I don't know, but I would guess for an old weakness

2022-03-18 15:58 UTC, juuz0 commented
https://github.com/kiwix/libkiwix/pull/465
Probably this
the method added into this explicitly defines no escaping `{{{searchURL}}}`

2022-03-18 18:00 UTC, legoktm commented
Thanks, so https://github.com/kiwix/libkiwix/commit/a59787002510a52171684487a10562d8d096c421 was only included in 10.0.0 (no released Debian versions are affected, just unstable).

Could we do a 10.0.2 release with just this cherry-picked? I note that even library.kiwix.org is vulnerable to this. Or if 10.1.0 is coming pretty soon then waiting wouldn't be too bad.

And we should also get a CVE ID assigned for this vulnerability, @kelson42 if you haven't gone through this [process](https://cveform.mitre.org/) before I'm happy to help out.

2022-03-19 08:17 UTC, kelson42 commented
@legoktm Thx for your last comment. For the moment I don’t have a strong opinion on this but understand the rationals. It seems as well your have a clearer opinion on the next release than I do. But, considering this PR to be closed, could you please open a new ticket with this arguments and why you woukd like to request early release of 10.1.0?