Automatic discovery of i18n resources
kiwix/libkiwix pull request #763
Opened 2022-05-01 18:31 UTC by veloman-yunkan

Excluding qqq.json any .json file under static/i18n is now considered to be a i18n resource. This eliminates the need to update the
i18n_resources_list.txt file every time a new language json file is added. Thus Translatewiki PRs will not require extra work.

2022-05-07 04:56 UTC, kelson42 commented
@mgautierfr Can you please review this PR?

2022-05-09 09:54 UTC, mgautierfr requested changes

2022-05-09 09:55 UTC, mgautierfr commented
> @mgautierfr Can you please review this PR?

Sorry, I had my review pending since last week and never push the send button

2022-05-09 11:25 UTC, veloman-yunkan commented on static/meson.build
> +])
I considered the multiline string option from the very beginning, but read [`meson`'s documentation](https://mesonbuild.com/Syntax.html#strings-running-over-multiple-lines) somewhat inattentively and concluded that support for multiline strings was added only in version 0.63 (actually that statement  pertains only to multiline f-strings). Fixed that.

What about the solution based on `pathlib.Path` - it doesn't work in my environment where the build directory (e.g. `BUILD_native_static/libkiwix`) is replaced with a symlink to a temporary directory located in ramfs (this is done in order to spare the SSD storage from wear caused by my work style - the code is automatically compiled and the unit-tests are run on every saved change). So I've preserved the original script.

2022-05-09 13:11 UTC, merged

2022-05-09 13:11 UTC, mgautierfr commented on static/meson.build
> +])
It is strange, symlink should not impact this. Anyway, we are good.

2022-05-09 21:11 UTC, eli-schwartz commented
https://mesonbuild.com/FAQ.html#but-i-really-want-to-use-wildcards

Note that re-running the build will NOT detect new files anymore.

The old file manifest method did not either, but it could have been made to work. https://mesonbuild.com/Fs-module.html#read

Instead of using a complicated `run_command()` to read out that file and turn it into an array, you would do

```meson
fs = import('fs')

i18n_resource_files = fs.read('i18n_resources_list.txt').strip().split('\n')
```

And modifications to that file would trigger a buildsystem reconfigure to detect new data used in the build configuration.

2022-05-10 07:36 UTC, veloman-yunkan commented
@eli-schwartz 

> Note that re-running the build will NOT detect new files anymore.

That's correct. 

> The old file manifest method did not either, but it could have been made to work.

There is a workaround to the new method as well - you only have to touch (update the last modification timestamp of) `static/meson.build` before re-running the build (this action can be considered as an equivalent of having to update the `i18n_resources_list.txt` file).

2022-05-10 08:25 UTC, mgautierfr commented
Indeed. Good catch, thanks.

> The old file manifest method did not either, but it could have been made to work. [mesonbuild.com/Fs-module.html#read](https://mesonbuild.com/Fs-module.html#read)

I did know about fs module. Thank again for the share

> you only have to touch (update the last modification timestamp of) static/meson.build before re-running the build (this action can be considered as an equivalent of having to update the i18n_resources_list.txt file).

I understand the logic behind this but I would never think about it.
But git doesn't store timestamps. It will work for local directory but CI running with cache will miss this timestamp modification. We could really change the content of `static/meson.build` by adding/removing a empty line but it would be some kind of ugly workaround.

I think the proper solution is to have a script generating `i18n_resources_list.txt` correctly (as it is done in [kiwix-desktop](https://github.com/kiwix/kiwix-desktop/blob/master/resources/generate_translation_qrc.py)) and run it regularly (at least in the release process)

2022-05-10 20:24 UTC, eli-schwartz commented
> There is a workaround to the new method as well

The old method could be made to ***work***, not work "around". Manually touching files after you git pull is not an equivalent of having to update the txt file. Updating the txt file is *reliable* in the sense that it always guarantees you are building whatever the txt file says to build, regardless of whether you configured the build and then `git pull`ed, or the other way around.

Touching the meson.build file in order to recalculate impure inputs means that people will unpredictably have "it built but the results didn't work" issues.

Maintaining a reliable manifest read by the fs module means that the build is *always* predictable, although some might feel it annoying to have to maintain that file. You could validate it in CI at least, though.