[WIP] Use available space for book element
kiwix/libkiwix pull request #786
Opened 2022-06-23 09:54 UTC by juuz0

Now we compute the available space in .book__list and if its bigger than half of a book element, the padding from both sides is reduced by a certain amount to accomodate the new element.
Fixes https://github.com/kiwix/kiwix-tools/issues/538

Before:
![image](https://user-images.githubusercontent.com/26814569/175271737-58ced8d4-1487-40e3-9cba-dd148422f172.png)

Now:
![image](https://user-images.githubusercontent.com/26814569/175271588-68fb4def-a707-4f46-878c-6715f7c85c57.png)

2022-06-23 10:00 UTC, juuz0 commented
Though this can be tested from a user-perspective, I have to check something in code hence the WIP status :+1:

2022-06-25 19:57 UTC, kelson42 commented
@juuz0 Thank you for your PR, but I can’t believe this is the right approach. Far too complex and no padding change should be necessary.

2022-06-27 15:36 UTC, mgautierfr commented
In https://svelte.dev/repl/2b6fd14cbd454b339dc8c55ea32d67e0?version=3.48.0 I've simply use a flexbox. The flexbox "compute" the best number of columns and adjust the padding/margin to have a proper layout.
There is no complex computation on our side.
You can try it by changing the width of the result preview.

2022-06-29 09:45 UTC, juuz0 commented
@kelson42 ping for re-review

2022-07-03 13:33 UTC, kelson42 requested changes
@juuz0 Thank you for this new PR which seems really more reasonable. I few remarks:
* My personal main problem was the problem visiblem on my iPad. It seems to be fixed now.
* I have added a commit to better align the filters on the left. Hope this is OK for you.
* I want the "number of books" title align left to the tile at the very left
* On my computer I think the margin left and right are still too big (see screenshot). Why there is not one additional tile in the row? 
![image](https://user-images.githubusercontent.com/1029718/177042103-02c17685-505f-4cf2-8752-493c4f794241.png)

2022-07-04 19:38 UTC, juuz0 commented
I have removed the centering layout, this is back to normal with a reduced left and right space.
Centring the tiles caused the problem with label, if there were 1 tile, 2 tiles, ....X tiles, it had to be changed all the time. Not easy to calculate correctly.

>  have added a commit to better align the filters on the left. Hope this is OK for you.

Yes, looks better.

![image](https://user-images.githubusercontent.com/26814569/177209453-d9c97a60-4549-40f4-866c-69ef5410be7f.png)
![image](https://user-images.githubusercontent.com/26814569/177209505-a7f3f762-2470-42cd-86e0-00756b300abf.png)

2022-07-05 08:30 UTC, kelson42 commented
@juuz0 This is what I get:
![image](https://user-images.githubusercontent.com/1029718/177285204-f49e5001-b9f1-43f5-9bc6-1028c3ec6a78.png)

* Margin right bigger than margin left
* There is still place for one tile

I'm not against center the tiles, but secure the "X books" title is aligned to the most left tile

2022-07-07 08:00 UTC, juuz0 commented
@kelson42 Review ping

2022-07-11 09:42 UTC, kelson42 commented
@juuz0 title is ok, but second problem is not fixed,
![image](https://user-images.githubusercontent.com/1029718/178236439-479115bd-4428-4d61-85dc-c1aa00c04a60.png)

There is still plently of place for an additional tile in a row. Why you don't reduce the margins left and right?!

2022-07-13 05:31 UTC, juuz0 commented
@kelson42 One more review ping :'D

2022-07-20 17:41 UTC, kelson42 approved these changes
From a user perspective, it finally works fine!

2022-07-20 17:41 UTC, merged